#!/usr/bin/env bash

###############################################
#
# Title:       avl-obsidian-sync
# Author:      Arne Van Looveren
# Description: Syncs obsidian to git repository
#
# Usage:       avl-obsidian-sync [commit_message]
#
###############################################
#
# Note:
# This script needs AVL_SCRIPTS_OBSIDIAN_VAULT_PATH to be set.
#
###############################################

DEFAULT_COMMIT_MESSAGE=notes

# Check if git is installed
if ! command -v git &> /dev/null; then
    echo "Error: git is not installed. Please install git to use this script."
    exit 1
fi

# Check if vault path is set
if [ -z "$AVL_SCRIPTS_OBSIDIAN_VAULT_PATH" ]; then
    echo "Error: AVL_SCRIPTS_OBSIDIAN_VAULT_PATH is not set. Please set the AVL_SCRIPTS_OBSIDIAN_VAULT_PATH variable to your Obsidian vault path."
    exit 1
fi

# Change to the vault directory
cd "$AVL_SCRIPTS_OBSIDIAN_VAULT_PATH" || {
  echo "Error: Could not navigate to $AVL_SCRIPTS_OBSIDIAN_VAULT_PATH."
  exit 1
}

# Check if the directory is a git repository
if [ ! -d ".git" ]; then
    echo "Error: this directory is not a git repository."
    exit 1
fi

# Fetch and pull latest changes from remote repository
if [[ $(git fetch --all &> /dev/null) -ne 0 ]]; then
    echo "Error: failed to fetch changes from remote repository. Please check your network connection and git configuration."
    exit 1
fi
if [[ $(git pull &> /dev/null) -ne 0 ]]; then
    echo "Error: failed to pull changes from remote repository. Please check your network connection and git configuration."
    exit 1
fi

# Create commit
if [ -z "$(git status --porcelain)" ]; then
    echo "No changes to commit."
    exit 0
fi

git add . &> /dev/null

if [[ $(git commit -m "${1:-$DEFAULT_COMMIT_MESSAGE}" &> /dev/null) -ne 0 ]]; then
    echo "Error: failed to commit changes. Please check your git configuration."
    exit 1
fi

echo "Created commit with message: ${1:-$DEFAULT_COMMIT_MESSAGE}"

# Push changes to remote repository
if [[ $(git push &> /dev/null) -ne 0 ]]; then
    echo " Error: failed to push changes to remote repository. Please check your network connection and git configuration."
    exit 1
fi

echo "Obsidian vault synced successfully to git repository."
