#!/usr/bin/env bash

###############################################
#
# Title:       hyprsunset-toggle
# Author:      Arne Van Looveren
# Description: Toggle script for hyprsunset blue light filter
#
# Usage:       hyprsunset-toggle
#
###############################################
#
# Note:
# This script needs hyprsunset to be installed.
#
###############################################

if ! command -v hyprsunset &> /dev/null; then
    echo "Error: hyprsunset is not installed. Please install hyprsunset to use this script."
    exit 1
fi

TEMP=4000

if pgrep -x "hyprsunset" > /dev/null; then
    pkill -x hyprsunset &> /dev/null
    notify-send "Hyprsunset" "Blue light filter disabled"
else
    hyprsunset -t $TEMP &> /dev/null &
    notify-send "Hyprsunset" "Blue light filter enables ($TEMP K)"
fi
