on:
  push:
    branches:
      - main

name: "Linting"

jobs:
  shellcheck:
    name: Shellcheck
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install Shellcheck
        run: sudo apt-get install -y shellcheck

      - name: Run Shellcheck
        run: |
          # Find all shell scripts in the repository, excluding .git and .github directories
          # and run shellcheck on them
          # Print the files being checked
          echo "Checking shell scripts..."
          find . -type f -name "*" ! -path "./.git/*" ! -path "./.github/*" -print0 | xargs -0 shellcheck --enable=all --severity=warning
