on:
  push:
    branches:
      - main

name: "Linting"

jobs:
  shellcheck:
    name: Shellcheck
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install Shellcheck
        run: sudo apt-get update && sudo apt-get install -y shellcheck

      - name: Run Shellcheck
        run: |
          echo "Running shellcheck on all files except .git and .github..."
          find . \
            -type f \
            ! -path "./.git/*" \
            ! -path "./.github/*" \
            -print0 \
          | xargs -0 --no-run-if-empty shellcheck --enable=all --severity=warning

